version: "2"
services:
  dispatcher-master:
    image: comnetunb/dispatcher-master:latest
    restart: unless-stopped
    container_name: dispatcher-master
    environment:
      - NODE_ENV=production
      - DB_HOST=dispatcher-mongodb
      - DB_DATA=ons
      - DB_PORT=27017
      - WEB_API_PORT=${DISPATCHER_MASTER_WEB_API_PORT}
      - WORKER_API_PORT=${DISPATCHER_MASTER_WORKER_API_PORT}
      - AUTH_SECRET_KEY=${DISPATCHER_MASTER_SECRET_KEY}
    ports:
      - ${DISPATCHER_MASTER_WEB_API_PORT}:${DISPATCHER_MASTER_WEB_API_PORT}
      - ${DISPATCHER_MASTER_WORKER_API_PORT}:${DISPATCHER_MASTER_WORKER_API_PORT}
    depends_on:
      - dispatcher-mongodb
  dispatcher-mongodb:
    image: mongo:latest
    container_name: "dispatcher-mongodb"
    restart: unless-stopped
    environment:
      - MONGO_DATA_DIR=/data/db
    volumes:
      - mongodb_data_container:/data/db

volumes:
  mongodb_data_container:
